### PR TITLE
Support for 1.20.5/6

### PR DESCRIPTION
**Pull request by SirYwell**
## Description

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Comment by rwnd-bradley** [comment]
Fails to build with `./gradlew clean build`:
```
FastAsyncWorldEdit\worldedit-bukkit\src\main\java\com\sk89q\bukkit\util\CommandRegistration.java:103: error: constructor SimpleCommandMap in class SimpleCommandMap cannot be applied to given types;
            fallbackCommands = commandMap = new SimpleCommandMap(Bukkit.getServer());
                                            ^
  required: Server,Map<String,Command>
  found:    Server
  reason: actual and formal argument lists differ in length
```

**Comment by SirYwell** [comment]
Seems like Paper broke API compatibility with https://github.com/PaperMC/Paper/pull/8235

**Review by NotMyFault — APPROVED** [review]
Is this ready to be merged?

**Comment by SirYwell** [comment]
I think so
