### ISSUE TITLE
FAWE causing WorldGuard region flag (deny-spawn) to fail

### ISSUE THREAD

**Issue by WOSK24** [IntellectualSites/FastAsyncWorldEdit#2766]
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

After updating both WorldGuard and FAWE to 1.20.6 my deny-spawn flag was removed and upon trying to redo that flag and reloading WG this error is given:

[16:16:59 WARN]: [WorldGuard] Failed to marshal flag value for SetFlag{name='deny-spawn'}; value is [minecraft:blaze, minecraft:skeleton, minecraft:zoglin, minecraft:ghast, minecraft:hoglin, minecraft:vindicator, minecraft:magma_cube, minecraft:piglin_brute, minecraft:spider, minecraft:creeper, minecraft:warden, minecraft:wither, minecraft:evoker, minecraft:slime, minecraft:phantom, minecraft:witch, minecraft:wither_skeleton, minecraft:husk, minecraft:cave_spider, minecraft:enderman, minecraft:stray, minecraft:vex, minecraft:zombie, minecraft:drowned, minecraft:zombie_villager]
java.lang.NoSuchMethodError: 'java.lang.String com.sk89q.worldedit.registry.Keyed.id()'
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.flags.RegistryFlag.marshal(RegistryFlag.java:64) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.flags.RegistryFlag.marshal(RegistryFlag.java:31) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.flags.SetFlag.marshal(SetFlag.java:100) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.flags.SetFlag.marshal(SetFlag.java:35) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.flags.FlagUtil.marshal(FlagUtil.java:61) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.flags.FlagUtil.marshal(FlagUtil.java:50) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.getFlagData(YamlRegionFile.java:292) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.saveAll(YamlRegionFile.java:236) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.managers.RegionManager.save(RegionManager.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.managers.RegionManager.saveChanges(RegionManager.java:136) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.protection.managers.RegionContainerImpl$BackgroundSaver.run(RegionContainerImpl.java:245) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
        at java.base/java.util.TimerThread.run(Timer.java:516) ~[?:?]

### To Reproduce

1. Download the latest versions of WorldGuard and FAWE
2. Use the command: /rg flag -w "World" -h 3 region deny-spawn pig
3. Use command /wg reload
4. Error will be given in the console

### Expected behaviour

Enabling this region flag should make all the mobs stop spawning.

### Error log (if applicable)

https://paste.gg/p/anonymous/95f530ce64ec48599c37814bcd587b80

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bc96e72916ef45ec92f5c3efe82a2b87

### Fawe Version

2.10.1-SNAPSHOT-792;c095c49

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.
